### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by Genysys** [ChrisRAoW/mautic-rss-to-email-bundle#10]
I am trying to install this on a bitnami mautic installation hosted on google cloud.  after runnning

the git clone command, I get this error"

`Could not scan for classes inside "app/AppKernel.php" which does not appear to be a file nor a folder `

Would appreciate any pointers on this

**Comment by ChrisRAoW** [comment]
From which folder are you running the git clone command?

**Comment by ChrisRAoW** [comment]
No response, closing issue.
