### ISSUE TITLE
Installation Failure not enough Memory

### ISSUE THREAD

**Issue by Ticodillo** [ChrisRAoW/mautic-rss-to-email-bundle#11]
Hi, I am trying to install on a siteground shared account and the memory limit for the account is 768 MB apparently the composer uses 845mb.  I am new Mautic, and would love to be able to use it but Rss to Email is a must for me,  is there a different way to install your plugin?

> Using version ^1.2 for raow/mautic-rss-to-email-bundle
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> 
> mmap() failed: [12] Cannot allocate memory
> 
> mmap() failed: [12] Cannot allocate memory
> 
> Fatal error: Out of memory (allocated 845160448) (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer.phar/src/Composer/DependencyResolver/Rule.php on line 76

```

**Comment by ChrisRAoW** [comment]
can you try to do the folowing. 

Run the following command In the root of your mautic installation:
`composer require simplepie/simplepie`

Download this ZIP:
https://github.com/ChrisRAoW/mautic-rss-to-email-bundle/archive/master.zip

Upload the folder in the plugins directory.

Please let me know

**Comment by Ticodillo** [comment]
Hey Chris, thanks for your response! I tried the command in the root like you asked and got the same error. It tried to allocate the same amount of memory, and the server threw the error.  
Thanks for taking the time on this. 

> theepoch@usm60 [~/public_html/marketing]# composer require simplepie/simplepie
> Using version ^1.5 for simplepie/simplepie
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> 
> mmap() failed: [12] Cannot allocate memory
> 
> mmap() failed: [12] Cannot allocate memory
> 
> Fatal error: Out of memory (allocated 845160448) (tried to allocate 20480 bytes) in phar:///usr/local/bin/composer.phar/src/Composer/DependencyResolver/Rule.php on line 76

**Comment by ChrisRAoW** [comment]
@Ticodillo Do you have other plugins installed was well? Does more sound like a composer configuration error or another package that is messing things up.

**Comment by Ticodillo** [comment]
I don't have any plugins installed. As far as the composer, I don't know what to say other than that it was a Softaculous install.

**Comment by ChrisRAoW** [comment]
@Ticodillo Sorry, since this is more server configuration, I can't help you any further.

**Comment by Ticodillo** [comment]
Hey Chris, no worries I understand, thanks for the help you gave.
