### ISSUE TITLE
Installing Plugin on cPanel instance without SSH

### ISSUE THREAD

**Issue by Shane-Bird** [ChrisRAoW/mautic-rss-to-email-bundle#12]
Ive uploaded the composer.json file as well as unzipped the plugin file in the root of the installation, what do i need to add to the composer.json file in order to be able to install the plugin within mautic with out having to run "composer require raow/mautic-rss-to-email-bundle"

**Comment by ChrisRAoW** [comment]
Currently not possible. But will try to make a versions available somewhere in the next few days that makes it possible to just upload the plugin in the plugins folder.

**Comment by ChrisRAoW** [comment]
@Shane-Bird  I just pushed a new version. Can you try to download the package from github and upload it to the plugins directory of Mautic? To be safe just follow the steps in the documentation.

**Comment by Shane-Bird** [comment]
Amazing! Thanks so much Chris!
