### ISSUE TITLE
Symfony/SimplePie issue after Mautic update

### ISSUE THREAD

**Issue by pradeepm** [ChrisRAoW/mautic-rss-to-email-bundle#13]
Hello Chris,

Since the latest Mautic update, I am getting this error. Any suggestions for a fix?

`mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "SimplePie" from the global namespace. Did you forget a "use" statement?" at /var/www/html/aofanews/plugins/MauticRssToEmailBundle/Feed/Feed.php line 12 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"SimplePie\" from the global namespace.\nDid you forget a \"use\" statement? at /var/www/html/aofanews/plugins/MauticRssToEmailBundle/Feed/Feed.php:12)"}`

Thanks and regards,

**Comment by ChrisRAoW** [comment]
Reinstall the plug-in should work.

Verstuurd vanaf mijn iPhone

**Comment by pradeepm** [comment]
Worked like a charm! Many thanks!

**Comment by milosrusov** [comment]
Hi guys, can you please tell me how to install simplepie by using compoer? Composer just kills the process.

**Comment by ChrisRAoW** [comment]
@milosrusov I know what you know. I already want to imclude the library into this plugin so you only have to install it once and stay safe on Mautic update. Haven't had the time you to fix. Will try to push it through this week.

**Comment by milosrusov** [comment]
Thank you so much Chris! :)

**Comment by ChrisRAoW** [comment]
@milosrusov I just pushed a new version. Can you try to download the package from github and upload it to the plugins directory of Mautic? To be safe just follow the steps in the documentation.

**Comment by milosrusov** [comment]
Works like a charm! :D Thank you once again!
