### ISSUE TITLE
Feed not working

### ISSUE THREAD

**Issue by developerdiary** [ChrisRAoW/mautic-rss-to-email-bundle#15]
Adding code in Code Block 

```
{feed url="https://www.theverge.com/rss/index.xml"}
    {feeditems count="3"}
        <h3>{feeditem:title}</h3>
        <p><small>{feeditem:date format="d-m-Y H:i"}</small></p>
        <p>{feeditem:description}</p>
    {/feeditems}
{/feed}
```

**Getting Output**

{feed url="https://www.theverge.com/rss/index.xml"} {feeditems count="3"}
{feeditem:title}
{feeditem:date format="d-m-Y H:i"}

{feeditem:description}

{/feeditems} {/feed}

Please help {feed url="https://www.theverge.com/rss/index.xml"} {feeditems count="3"}
{feeditem:title}
{feeditem:date format="d-m-Y H:i"}

{feeditem:description}

{/feeditems} {/feed}

Mautic Version : 2.14.2 (Still not working)

**Comment by ChrisRAoW** [comment]
Hi @developerdiary, look like the plugin isn't active yet. Did you activated it after installing it into the plugins folder?

**Comment by ChrisRAoW** [comment]
No, repsonse, So I assume it's no issue anymore.
