### ISSUE TITLE
Low res images in feed

### ISSUE THREAD

**Issue by Mamebart** [ChrisRAoW/mautic-rss-to-email-bundle#19]
Hi,

I've noticed that {feeditem:image} pulls in low res images from my feed (https://androidworld.be/feed). Here's the code that loads the image:

`<img src="https://cdn3.androidworld.nl/media/thumbnails/47/94/4794d7ce6ea2b61f46c9f347f3b831f0.jpg" alt="content image" data-pagespeed-url-hash="3429114804" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"/>`

With the same feed, in Feedly the high res images are loaded. How can I load the high res images in my Mautic/RSS email?

Thanks.

**Comment by ChrisRAoW** [comment]
@Mamebart It's using the url in the `<enclosure>` tag. There the low-res image is sent.
