### ISSUE TITLE
[Feature Request] Conditional Tags

### ISSUE THREAD

**Issue by justlevine** [ChrisRAoW/mautic-rss-to-email-bundle#2]
Would love to see a future release include conditional tags.
Something along the lines of `{iffeed:tag_name == 'value'} <div> ...{feeditem...}</div> {/iffeed}`.
Could be similar to [Mailchimp's Conditional Merge Tags](https://kb.mailchimp.com/merge-tags/use-conditional-merge-tag-blocks), just testing the $content returned from ItemsParser.php

I'm out of the country for the next few months, but I will happily write the PR when I'm back in June (if no one beats me to it)

**Comment by ChrisRAoW** [comment]
Thanks for your idea. Will put it on the todo, but am really busy with client work at the moment

**Comment by eugusouza** [comment]
Hello @ChrisRAoW congratulations for this plugin, but the smae don't work in anyone version.

I tested in 2.12, 2.12.1, 2.13 and 2.13.1 and nothing.

Best regards.

**Comment by ChrisRAoW** [comment]
It was created in version 2.12. So it will certainly work. What do you experience?

**Comment by eugusouza** [comment]
By the way... In 2.12 it's not working.

When sending the test email it was processing forever and nothing.

When sending the e-mail to some of my team's contacts, it was processing forever and nothing.

That is, it did not work at all.

PS: I always use segment email for testing.

**Comment by ChrisRAoW** [comment]
Did you check the error log?

**Comment by eugusouza** [comment]
Yeah...

Error in line 12 Folder "Feed" file "Feed.php" $feed = new SimplePie();

**Comment by ChrisRAoW** [comment]
Can you check if your vendor folder contains a simplepie folder?

**Comment by eugusouza** [comment]
The "Simplepie" folder doesn't exist.

**Comment by ChrisRAoW** [comment]
That's your problem. Did you install the plugin through composer? (following the instructions on github)?

**Comment by eugusouza** [comment]
Yes. Absolutely the same.

But anyway, I'm now in version 13.1.

Can you tell me if it works on her?

**Comment by ChrisRAoW** [comment]
Got the same issue now. Will try to fix tonight.

**Comment by eugusouza** [comment]
Ok. Can you inform me of the correction and update, please?

**Comment by ChrisRAoW** [comment]
Nevermind, it is working in 2.13.1 as it is. But after update you have to run the composer command again from the mautic root `composer require raow/mautic-rss-to-email-bundle`

**Comment by ChrisRAoW** [comment]
@eugusouza Is it workingfor you now?

**Comment by eugusouza** [comment]
@ChrisRAoW the same problem in Mautic 13.1.

And now, the system is shoutdown when insert your plugin.

**Comment by ChrisRAoW** [comment]
@eugusouza Can you find something in the log-files?

**Comment by eugusouza** [comment]
@ChrisRAoW I could not even see it, because when I installed it in version 13.1, it returned error 500 and I could not even open the Mautic.

In order to run, I had to delete your plugin. Only then did it work again.

**Comment by eugusouza** [comment]
@ChrisRAoW now it's running ok.

Any question. I use the code in Campaign Email or Segment Email.

How it works better?
