### ISSUE TITLE
Does this work with Mautic 2.15?

### ISSUE THREAD

**Issue by 3ruce** [ChrisRAoW/mautic-rss-to-email-bundle#20]
Great plugin! I just upgraded to v. 2.15, do you know if this will still be compatible?

**Comment by ChrisRAoW** [comment]
@3ruce Thanks! Yes it is!

**Comment by 3ruce** [comment]
Cool, thank you!

**Comment by arthurocrates** [comment]
i waiting...

**Comment by ChrisRAoW** [comment]
@arthurocrates what for?
