### ISSUE TITLE
Cannot install in Mautic 2.15.2-dev

### ISSUE THREAD

**Issue by afanjul** [ChrisRAoW/mautic-rss-to-email-bundle#21]
Hi there, I'm trying to install this plugin into Mautic 2.15.2-dev and it does not show in the plugins list, here are my steps without any success:

- git clone the repository
- rename the folder to MauticRssToEmailBundle inside /var/www/mautic/plugins folder
- be sure that the owner is www-data 
- go to plugins sections and press the button to "install/upgrade" plugins

But the plugin doesn't show at all...  any clues?

**Comment by ChrisRAoW** [comment]
@afanjul Did you already try to clear the cache?

**Comment by afanjul** [comment]
Yes, I cleaned the cache... but no way...

**Comment by ChrisRAoW** [comment]
@afanjul have you already tried to install other plugins?

**Comment by afanjul** [comment]
Hi @ChrisRAoW, many thanks for your suggestion because after copying another "dummy plugin" like "Advanced Templates", and empty (this time just the "prod" folder inside cache), and refreshing the extensions, now the rss extension appeared.... 
A very strange behaviour... I don't know if its the way I emptied the cache folder, or just the insertion of a new plugin... 
strange things! but thanks
