### ISSUE TITLE
THANK YOU FOR THIS MODULE

### ISSUE THREAD

**Issue by pwilhelm949** [ChrisRAoW/mautic-rss-to-email-bundle#22]
Just wanted to leave this here to say thank you. You are a life saver. This plugin works beautifully. 

It's been a long time coming and it's finally here, I had wanted something like this wayback in 2015.

Great work again Chris!

**Comment by ChrisRAoW** [comment]
@pwilhelm949 Thanks for you kind words! Very much appreciated!
