### ISSUE TITLE
Send a daily or weekly email using feed items

### ISSUE THREAD

**Issue by 3ruce** [ChrisRAoW/mautic-rss-to-email-bundle#23]
So I'm probably missing something here, but having got the plugin working fine in a test email, what sort of campaign do I setup so that mautic keeps sending a daily or weekly email from the rss feed?

**Comment by ChrisRAoW** [comment]
This not really a question regarding this plugin, but is related to how mautic works. Maybe better to ask for help on slack for example.

**Comment by 3ruce** [comment]
Cool, I think the "restart campaign" feature does the trick...

* https://github.com/mautic/mautic/pull/6132
* https://github.com/mautic/mautic/issues/1606

There's also a demo here...

* https://navigatetomorrow.com/tutorials/how-to-create-a-birthday-campaign-in-mautic
