### ISSUE TITLE
Feature request: Reverse order

### ISSUE THREAD

**Issue by TBarregren** [ChrisRAoW/mautic-rss-to-email-bundle#26]
I suggest that the tag`{feeditems}` gets a flag `reverse` to control the sort order of the outputted items. If present, the items are outputted in reverse order.

Usually, RSS feeds lists items in reverse chronological order. But in a newsletter it would be nice to present them in chronological order. With this flag it would be possible.

**Comment by ChrisRAoW** [comment]
@TBarregren Good suggestion, will think about it.

**Comment by ChrisRAoW** [comment]
This one is in latest release. Thanks @kuzmany
