### ISSUE TITLE
Installing on 2.15.3 the RSS code renders nothing.

### ISSUE THREAD

**Issue by pleasemarkdarkly** [ChrisRAoW/mautic-rss-to-email-bundle#28]
Tried to test this plugin, and after updating my docker container with the compose file and installing the plugin, the drop in code example failed to render anything on my tests, are there areas or logs which I can inspect what is going on?

**Comment by ChrisRAoW** [comment]
@pleasemarkdarkly Mhh, strange. Have plugin here running without issues. You're sure the Feed isn't empty?

**Comment by pleasemarkdarkly** [comment]
That was the first thing I checked, moved it to a few open source feeds and ycombinator.

-Sent from my iPhone; sorry for ayn typos.

**Comment by ChrisRAoW** [comment]
have you used the plugin before without issues?

**Comment by pleasemarkdarkly** [comment]
No, installed it on a fairly new installation. 

Mark

-Sent from my iPhone; sorry for ayn typos.

**Comment by ChrisRAoW** [comment]
But if I understand correctly, the tokens are replaced, but basically with nothing?

**Comment by pleasemarkdarkly** [comment]
Yes, empty. The files were copied properly, permissions were set properly, it installed, and the sample tokens were included as directed.

**Comment by ChrisRAoW** [comment]
Can you copy / paste the template? Just to be sure?
