### ISSUE TITLE
{feeditem:image} not pulling image

### ISSUE THREAD

**Issue by christianschubert76** [ChrisRAoW/mautic-rss-to-email-bundle#29]
Hello, this might not be an issue code wise - maybe we have to change our rss feed output:

Our site includes image like this within the RSS XML
<item>
<media:thumbnail url="webserver.com/thumbnail.jpg"/>
</item>

The URLs are working fine and show the thumbnail image. What do we have to do to make it work in mautic?

**Comment by YouBuiltThat** [comment]
I am using a WordPress RSS feed and similar issue Everything works but the image.

I am in 2.16.0_beta but this seems to be the only issue.  This may be that the RSS is not able to parse the default WP image information.

**Comment by YouBuiltThat** [comment]
> I am using a WordPress RSS feed and similar issue Everything works but the image.
> 
> I am in 2.16.0_beta but this seems to be the only issue. This may be that the RSS is not able to parse the default WP image information.

Nevermind I decided to grab a half dozen more WP sites and most of those work flawlessly clearly for me it is just not working with the RSS from my sites.

**Comment by ChrisRAoW** [comment]
Do you have a rss feed for me where I can run some tests with?

**Comment by christianschubert76** [comment]
@ChrisRAoW Hi, this is our self-generated RSS feed - we have full control over the possible output

https://www.esanum.de/rss/feeds/today

Thanks for your help!

**Comment by ChrisRAoW** [comment]
Can you test with media:content in stead of media:thumbnail?

Chris

**Comment by christianschubert76** [comment]
@ChrisRAoW thanks this works - we added this to our output.
