### ISSUE TITLE
Not showing in Mautic v2.16.2

### ISSUE THREAD

**Issue by ashishpatel1992** [ChrisRAoW/mautic-rss-to-email-bundle#34]
This plugin is not visible in Mautic v2.16.2
I have extracted the files in directory /plugins
and renamed the folder as MauticRssToEmailBundle
But it doesnt display in Mautic GUI / Plugins

**Comment by ChrisRAoW** [comment]
Already tried to clear the cache?

**Comment by ashishpatel1992** [comment]
Yes cleared the cache at _/app/cache_
But doesnt help

**Comment by ChrisRAoW** [comment]
Did you had the plugin already before?

**Comment by ashishpatel1992** [comment]
No. I just installed it on a fresh site with fresh Mautic Installation

**Comment by Horlaes** [comment]
I have the same issue, please help

**Comment by ericcumbee** [comment]
Having the same issue on a fresh install as well.

**Comment by ericcumbee** [comment]
apparently I poked my install with a stick enough to make it work.

**Comment by MyWebmasterD** [comment]
same in mautic 2.15. not showing in plugin list

**Comment by ChrisRAoW** [comment]
@MyWebmasterD Probably you have to clear the cache and go to he install/upgrade page.

**Comment by MyWebmasterD** [comment]
Yes clearing the cache solved the issue

**Comment by MyWebmasterD** [comment]
The feed perfectly works, do you know how to trigger the email when a new post is published?

**Comment by GMCenterprises** [comment]
this works perfectly in version 3

https://mauticapps.com/
