### ISSUE TITLE
Not Working In Mautic 3

### ISSUE THREAD

**Issue by EmprendoHub** [ChrisRAoW/mautic-rss-to-email-bundle#35]
Hi there, just wanted to report that I tested this plugin in the new Mautic 3 and it's not working, is there any plans of updating the code so it's compatible with the new Mautic 3 version?

**Comment by ChrisRAoW** [comment]
@EmprendoHub Yes, absolutely. Didn't had the time yet to check it out. Will will try soon. Thanks for you report.

**Comment by alessiofx** [comment]
i have some problem ! Follow

**Comment by arnoldsigik** [comment]
Hmm.. I bumped to a problem too. Probably the same as I have version 3 of Mautic. So I tried to install this: https://github.com/ChrisRAoW/mautic-rss-to-email-bundle and follow the instruction here:

Installation:
1. Download the plugin from github
2. Move / Upload folder to the plugins directory. Name the folder MauticRssToEmailBundle
3. In the Mautic GUI, go to the gear and then to Plugins.
4. Click on the "Install/Upgrade Plugins" button
5. You should now see the "Rss To Email" in your list of plugins.

Stuck into #4 & 5 as the "Install/Upgrade Plugins" button keeps saying 0 install. I can't see the "Rss To Email" in my list of plugins. Any idea? Crobjobs? I have set these to run one by one:
- mautic:plugins:reload 
- mautic:plugins:install 
- mautic:plugins:update

for every minute but none of them get me to show the "Rss To Email" in my list of plugins.

**Comment by GMCenterprises** [comment]
Any news on the possibility of getting this plug-in working in Version 3?

**Comment by GMCenterprises** [comment]
> Any news on the possibility of getting this plug-in working in Version 3?

I'm not sure if this is related but it works perfectly fine for me in Mautic Ver 3

https://mauticapps.com/

**Comment by connectedbusiness-gary** [comment]
> > Any news on the possibility of getting this plug-in working in Version 3?
> 
> I'm not sure if this is related but it works perfectly fine for me in Mautic Ver 3
> 
> https://mauticapps.com/

I can confirm that this works in version 3.3.1

**Comment by ChrisRAoW** [comment]
The plugin now works with mautic 3.3.2. Thanks to @kuzmany!

**Comment by TonyBogdanov** [comment]
@ChrisRAoW Does this mean the plugin works **only** in Mautic 2.* and Mautic 3.3.2+?

**Comment by ChrisRAoW** [comment]
@TonyBogdanov Yes, it should.
