### ISSUE TITLE
Cannot declare class MauticPlugin\GrapesJsBuilderBundle\GrapesJsBuilderBundle, because the name is already in use

### ISSUE THREAD

**Issue by TonyBogdanov** [ChrisRAoW/mautic-rss-to-email-bundle#38]
When I install this plugin with `composer require` I get the above error during `cache:clear`.

I'm pretty sure it's caused by this line: https://github.com/ChrisRAoW/mautic-rss-to-email-bundle/blob/d5532047642b54129690fc18625a372f75ca678c/MauticRssToEmailBundle.php#L20

What's it's purpose? Mautic already uses the composer autoloader (at least in development mode). If this is some weird edge case, it should at least be `include_once`.

**Comment by TonyBogdanov** [comment]
Actually I just realised this references some custom loader within the plugin, but the above issue is still quite real.
I forgot to mention that this happens with Mautic 3.3.2.

**Comment by TonyBogdanov** [comment]
Just did some more testing and it looks like **all** of this is already resolved in `master`. In fact, `master` installs beautifully in all of the following Mautic versions:
- `2.15.3`
- `2.16.4`
- `3.0.2`
- `3.1.2`
- `3.2.2`
- `3.2.4`
- `3.3.1`
- `3.3.2`

Perhaps you could just release it?

**Comment by ChrisRAoW** [comment]
@TonyBogdanov Good point. I tagged it version 1.5.
