### ISSUE TITLE
Not show up in plugins

### ISSUE THREAD

**Issue by diamondtheta** [ChrisRAoW/mautic-rss-to-email-bundle#39]
Hello!

I have uploaded the folder into plugins directory, but it do not showss up under plugins menu in mautic 3.3.2 :(
I have bought this plugin on mauticapps.com. Is that different from this?

Thanks,
Adrian

**Comment by ChrisRAoW** [comment]
@diamondtheta This plugin is not the one you bought on mauticapps.com. But did you clear the cache?

**Comment by diamondtheta** [comment]
Thanks! Clearing the cache worked :DD
I always forgot that solution :D
But what is the difference then if these mautic RSS plugins are different ?

**Comment by ChrisRAoW** [comment]
@diamondtheta I'm honestly not sure about the plugin on mauticapps. The only thing I know is that I made this one (on github) as open source and therefor publicly available. The one on mauticapps is paided. Not sure if its better....

**Comment by diamondtheta** [comment]
Then maybe someone just selling your opensource plugin there? :D
I only found this one after I bought that :D

**Comment by diamondtheta** [comment]
The files seemed the same O.O

**Comment by ChrisRAoW** [comment]
I thought about it, and never thought they would This is really ugly. Thanks for letting me know.

**Comment by diamondtheta** [comment]
I don't know that if it is ALL the same (i checked only the file names under the main directory), but you checked and those 2 are ALL the same??

**Comment by ChrisRAoW** [comment]
I didn't check...didn't bought the plugin ;-)

But even if they made change, they cant just copy code like this.

**Comment by diamondtheta** [comment]
It seems the same plugin to me also because of the installation guide and embeding tags also. :(
But if this is your plugin than maybe you are more aware about this issue:

Now I could insert images into my RSS but can't fetch it into the {feeditem:image}, but only into the {feeditem:description} !
So the image is NOT appearing with {feeditem:description}, and the image only appears with {feeditem:description} in the email WITH the description also!
But I don't want description! And this way I even can not put a link only to the image! I want to be able to put link only to the image and not on to the "image+description"! And I do NOT want description also so need to fetch image URL into {feeditem:image} and NOT into {feeditem:description} with description :( 

So I think there is a specific tested way to insert images into RSS, what is the rigth way?
I have tried with custom code copy paste from the net, and also with "Featured Images in RSS for Mailchimp & More" plugin but booth are with the same error I described now. :(

**Comment by ChrisRAoW** [comment]
@diamondtheta Can you send me the url to the feed.

**Comment by diamondtheta** [comment]
Ok, thanks, but I have solved ALL yesterday!! ;DD
This is my feed URL for example: https://orult.hu/nyelv-nelkul-is-ertheto/feed
So you can see that the RSS image should be output in this format, but could not find plugin or RSS code that did that, I had to customize code :D
Other than the image in RSS (what I wrote earlier) there was no other problem.

**Comment by ChrisRAoW** [comment]
Good to know. Have fun using this FREE plugin ;-) haha

**Comment by diamondtheta** [comment]
^^
