### ISSUE TITLE
How to setup Rss Email ongoing?

### ISSUE THREAD

**Issue by nroccogit** [ChrisRAoW/mautic-rss-to-email-bundle#41]
Hi, sorry if I use this channel but I think can be interesting for other users like me... new to Mautic.
I've setup the plugin and seem to work but... How can I set a "campaign" that send my RSS feed updates to a "segment" of contacts?

Can you update the docs and write how to use the plugin once installed? Need to create a "campaign"? a "segment"? an "segment email"? or what?

Thanks for your time. Really appreciated.

**Comment by ChrisRAoW** [comment]
@nroccogit This plugin works for e-mails. It doesnt matter what kind of e-mail you use. So you can create a segment and use that to send a segmented e-mail, or create a campaign and send an e-mail within that process.

**Comment by nroccogit** [comment]
@ChrisRAoW thanks for your quick reply. I've setup a broadcast email linked with a (for now) test segment with 2 contacts. Then I manually sent the email from the email "panel" to checkout the final result. Everything was ok.

Now:

- if I try to manually send again the email the send window says "There are no pending contacts.". So it seems that I can't send this email multiple times to the same contacts... but this is the final scope of this email
- I've tried to publish a new item on the RSS feed linked to the email. No email are sent out.

Maybe I miss some configuration? Is there a way to say "allow to send this email multiple times to the same contacts"?

Thanks again for your time.
Look forward your response.

**Comment by nroccogit** [comment]
@ChrisRAoW any idea? What is the ideal setup to make it works?

**Comment by ChrisRAoW** [comment]
@nroccogit Sorry, something went wrong with my reply.

At first, the plugin "simply" fetches the feed and displays the content in the e-mail. It doesnt trigger e-mails when new items arrive in the feed.

To send an e-mail to the same contact multiple times you can set up a campaign the check the "allow contacts to restart the campaign" checkbox. Everytime the contact appears in the segment the mail will be send out. 

You can also duplicate the segment e-mail and resend the e-mail like that.

**Comment by nroccogit** [comment]
@ChrisRAoW no problem... thanks for reply.
I think is my fault... I misunderstand the plugin functionality. I was expecting "trigger e-mails when new items arrive in the feed." :)
So this is not the right plugin for my use case.
By the way, I think it can be a good idea for future releases.
Thanks again for your time.
