### ISSUE TITLE
Question about performance/number of feed requests

### ISSUE THREAD

**Issue by iparker** [ChrisRAoW/mautic-rss-to-email-bundle#42]
Hello,

I have a short question about the performance when using the rss feed bundle:

When I send the email to multiple contacts, is the feed requested for every single contact or is there any kind of caching for this data to handle the request just one time?

Thanks for an short answer! 

Best regards,

Timo

**Comment by ChrisRAoW** [comment]
@iparker It's some time ago. But if I remember well it done only once on every batches. So if you have 1000 contacts and batches of 100 it will be called 10 times.

**Comment by iparker** [comment]
Great - thanks a lot for your reply!

**Comment by iparker** [comment]
Hi Chris,

hi have to re-ask for this issue. 

We use your rss-plugin very intensive to output different dynamic data in the emails.

The last thing we created was an rss-feed which generates a individual coupon code for each receiver. We realised this by an api-endpoint (in our system) which creates a new bonus-code and returns this code as rss-feed so we can output the code with your plugin. This endpoint get id-data from the contact.

Unfortunately we mentioned that we very less new bonus code entries in our database - and with that I remembered this issue with the batch-size.

I think this is the problem: In our usage/use case we expect that every single email will make an request to the feed url and output this individual data. 

But this is not how it works because the feed url is just requested once for every batch size.

Do you have any idea how we can solve this and change this behaviour? 

Is there any way to make this call for every receiver? Or something like to change the batch-size to 1?

Thanks for some ideas and help!

Best regards

Timo
