### ISSUE TITLE
Can someone offer me the development of a litte extension for this bundle?

### ISSUE THREAD

**Issue by iparker** [ChrisRAoW/mautic-rss-to-email-bundle#43]
Hello,

sorry for asking this at github: But can someone of the contributors offer me some small extensions for this bundle?

I would like to have an option to output some random feeditems. For example I have a feed with 20 items. I would like to define that I output just 5 from these 20 items random.

Another question: Is there a way to work with other data than rss feeds, for example another xml structure or event a json response from an api?

Thanks for some feedback!

Best regards,

Timo

**Comment by ChrisRAoW** [comment]
@iparker Selecting feeditems will be hard thing to do. I did it before at the other side. Within wordpress selecting the items I want to return in the feed.

Currently other data resources arent possible, but shoulld certainly be possible. Will think about that one. Do you have a specific use case in mind?

**Comment by iparker** [comment]
Thanks for your reply.

In best case we want to output data from an api backend (also symfony with api-platform). If this is not possible we can think about output this data as rss. But if json would be possible we don't have to change anything.

What do you mean with "selecting feeditems". I don't want to select special items but to output random items from a feed like

{feeditems count="10" shuffe}

In the feed-url I would define something like: myfeeed.rss?limit=30, so I get 30 items from the feed but just 10 of these items should be in the output by random.

Hope you can understand what I mean.

**Comment by ChrisRAoW** [comment]
@iparker Just added a `shuffle=1` parameter.
