### ISSUE TITLE
Output feed based on url from token?

### ISSUE THREAD

**Issue by iparker** [ChrisRAoW/mautic-rss-to-email-bundle#44]
Hello,

I want to specify the feed-url via an email token when I send emails with the rest api (see at https://developer.mautic.org/#extending-emails).

So I define the output of the feed like this:

`{feed url="{token_feed}"} {feeditems count="3"}`

But with this I get an error in the email like this:

Error: URL (https://ipm-promotion.de/feed/) empty or not valid 

There is the output of my feed-url but it could not be processed.

If I use the feed directly not with the token everything works fine. But the usage of the token is very important for me.

Do you have any ideas how to get this working?

Best regards,

Timo

**Comment by ChrisRAoW** [comment]
@iparker Interesting use case. Will try to reproduce and think of a fix.

**Comment by iparker** [comment]
Great - thank a lot for your quick feedback! That would be great if you could implement the possiblity to handle a feed url from the token!

**Comment by iparker** [comment]
Hello Chris,

don't know if you receive this message but it would be great if you 
could give me your email address for direct contact.

Maybe we can talk about my customization questions 
(https://github.com/ChrisRAoW/mautic-rss-to-email-bundle/issues/43).

It would be great to get feedback!

Best regards,

Timo


<https://ipm-promotion.de> 	*iPM_Promotion*
eine Software der *iPark-Media GmbH*
Timo Hähne
Geschäftsführer

iPark-Media GmbH
Am Heuskamp 35
31832 Springe 	Tel.: 0511 - 768 22 980
Fax.: 0511 - 768 22 988

E-Mail: ***@***.*** ***@***.***>
Webseite: www.ipark-media.de <https://www.ipark-media.de>
*iPM_Promotion und unser PromoVersum:*
<https://ipm-promotion.de/blog> 	*iPM_Promotion*: ipm-promotion.de 
<https://ipm-promotion.de>
Erfolgreiche Planung und Steuerung von Promotion, Absatzförderung und 
Events!

<https://ipm-promotion.de/blog> 	*PromoBlog*: ipm-promotion.de/blog 
<https://ipm-promotion.de/blog>
Artikel und News aus und für die Promotion-Branche
<https://hilfe.ipm-promotion.de> 	*PromoHilfe*: hilfe.ipm-promotion.de 
<https://hilfe.ipm-promotion.de>
Artikel und Tutorials zu iPM_Promotion
<https://wiki.ipm-promotion.de> 	*PromoWiki*: wiki.ipm-promotion.de 
<wiki.ipm-promotion.de>
Begriffserklärungen zur Promotion-Branche

Handelsregister
Hannover HBR 200422

USt.-IdNr.
DE 245178331 	Geschäftsführer
Timo Hähne



Am 20.07.21 um 12:19 schrieb ChrisRAoW:

**Comment by ChrisRAoW** [comment]
Can you send me an e-mail at chris[at]raow[dot]nl

**Comment by ChrisRAoW** [comment]
@iparker The "token_feed" token, where is it coming from in your example? Do you use the api to send out an e-mail? (https://developer.mautic.org/#send-email-to-contact)

**Comment by iparker** [comment]
Yes, the token comes from the api when sending an email to a single contact.

**Comment by ChrisRAoW** [comment]
@iparker Do you know what php version you're on?

**Comment by iparker** [comment]
Yes, php version 7.3.27 and mautic version 3.3.3.

**Comment by ChrisRAoW** [comment]
@iparker I just commited a change to the master branche that should make this possible. Can you check it out?

**Comment by iparker** [comment]
Hi Chris,

thanks a lot for your update! We updated your bundle and now the feed items are displayed when I add the feed url via token in send api. Thanks a lot!

Now we will test it with some real use cases.
