### ISSUE TITLE
Not showing full content, content and image

### ISSUE THREAD

**Issue by rodneyoliveira** [ChrisRAoW/mautic-rss-to-email-bundle#47]
Hi,

{feeditem:content_full_text}
{feeditem:content_full}
{feeditem:image}
{feeditem:content}

are not working here. Only {feeditem:content_text } is ok.

You can check rss email we used to send here:
https://comunica.lscadministradora.com.br/email/preview/15

Can u gimme a clue?

Thanks!!!!

**Comment by rodneyoliveira** [comment]
`     {feed url="https://lscadministradora.com.br/artigos/category/condominios/feed/"} {feeditems count="2"}
        <tr>
            <td style="text-align: left; padding: 15px 0px;">
              <tr>
                <td>{feeditem:image}</td>
              </tr>
                <tr>
                    <td style="text-align: left; padding: 0 15px;">
                        <h2>{feeditem:title}</h2>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: left; padding: 0 15px;">
                       
                    </td>
                </tr>
                <tr>
                    <td style="text-align: left; padding: 15px;">
                        <p>{feeditem:content_full_text}</p>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: left; padding: 0 15px;">
                        <a href="{feeditem:link}?utm_source=mautic4&utm_medium=email&utm_campaign=rss" class="linkleia">Leia Mais</a>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: left; padding: 0 15px;">
                        <hr>
                    </td>
                </tr>
            </td>
        </tr>
        {/feeditems} {/feed}`

**Comment by ChrisRAoW** [comment]
@rodneyoliveira You're feed seems to be "incomplete". I'm not seeing the <content> tag, which normally contains the full content. 

The image is a different story. I see you're using wordpress. To use the image tag the image should be provided in the rss feed in an `<enclosure>` or `<media>` tag. I think a plugin like this should help: https://nl.wordpress.org/plugins/wp-feed-post-thumbnail/

**Comment by rodneyoliveira** [comment]
@ChrisRAoW Thanks for your response. When you say incomplete, which tags are you referring to? I mean, what tags are missing to work properly?

**Comment by ChrisRAoW** [comment]
@rodneyoliveira The `<content>` tag for example

**Comment by ChrisRAoW** [comment]
Closed due to inactivity
