### ISSUE TITLE
Feedinfo:url

### ISSUE THREAD

**Issue by dougysobi** [ChrisRAoW/mautic-rss-to-email-bundle#5]
Hi,
I'm using your cool plugin through Mautic since a few days to blast my newsletter around that is generated with ttrss. It starts to work but I'm struggling with the {feedinfo:url}. Indeed, when I click on the title of one of the articles contained by the rss flow I'd like of course that it points to the source of the article but at the moment it points at the url of the rss flow instead... Any idea of why this happens and how to fix it?
Many thanks in advance!
Ju

**Comment by dougysobi** [comment]
Answering to myself as I solved the previous point that I raised, here is the slightly tweaked code of the php file caled "ItemTag.php" just add a case 'urlitem':
  switch ($this->tag) {
          //To point, within the Newsletter, towards full articles online. For this use <a href="{feeditem:urlitem}"> in your HTML code in Mautic
            case 'urlitem':
                $value = $feedItem->get_permalink();
                break;
            case 'title':
                $value = $feedItem->get_title();
                break;
      ...
...

**Comment by ChrisRAoW** [comment]
I see this tag is missing in the docmentation. Will add it: But you should be able to use {feeditem:link}
