### ISSUE TITLE
Custom fields in feeds

### ISSUE THREAD

**Issue by shmaltz** [ChrisRAoW/mautic-rss-to-email-bundle#51]
Hi!

I am creating a custom WP post feed that will contain custom fields.

Can these fields be accessed by using something like `{feeditem:custom_field}` or do I need to modify the plugin to read these fields?

Thanks!

**Comment by ChrisRAoW** [comment]
@shmaltz This is good feedback. You can't just add custom fields to you RSS feeds because it will invalidate the rss feeds because those fields don't exist for rss feeds. We can overcome this by defining a custom xmlns. Will put it on our dev-list.

**Comment by shmaltz** [comment]
Sounds great @ChrisRAoW!

Thank you!

Happy holidays!

**Comment by ChrisRAoW** [comment]
@shmaltz This was added in the latest 1.6.0 release. Check the ReadME file how to use it.
