### ISSUE TITLE
<image> tag

### ISSUE THREAD

**Issue by shmaltz** [ChrisRAoW/mautic-rss-to-email-bundle#52]
I have add an image to my RSS feed (WP) manually, and it shows up like this:
`<image><url>www.image-url.com</url></image>`
(The image isn't part of the content)

I tried adding the image to my email template using` {feeditem:image} `but it doesn't load.

Do I have to modify anything in my feed to make this work?

Thanks!

**Comment by ChrisRAoW** [comment]
It will check this `<media>` or `<enclosure>` tag in the rss.

**Comment by shmaltz** [comment]
Thank you. That helped.
