### ISSUE TITLE
Compatibility with V4.1.1

### ISSUE THREAD

**Issue by shmaltz** [ChrisRAoW/mautic-rss-to-email-bundle#54]
I recently updated to v4.1.1 and the plugin shows up in the plugin list, however it isn't converting the rss tags in my template to the proper text.

I added the tags into the template using "Edit Code" button, as v4.x doesn't seem to have the "code mode" slot like v3.

Am I doing something wrong?

Thanks!!

**Comment by shmaltz** [comment]
It looks like the new grapesjs editor stripped out the {feeditems} and {feed} tags, along with other styling info.

**Comment by ChrisRAoW** [comment]
@shmaltz Will dive into it.

**Comment by rmdes** [comment]
Same here can't get it work anymore :  Error: URL () empty or not valid

**Comment by ChrisRAoW** [comment]
@shmaltz @rmdes Sorry for my late reply, but I checked the plugin in latest version and everything is working fine. Will close this issue for now. If you still stumble upon a / the issue, feel free to open a new one.
