### ISSUE TITLE
Why not use api instead of RSS?

### ISSUE THREAD

**Issue by oguruma1218** [ChrisRAoW/mautic-rss-to-email-bundle#55]
I'm a coding and Mautic noobie, so please forgive me, but why not just use the Wordpress REST API to get the posts instead of an RSS feed? 

As I understand it, the API will give you completely granular control over which posts, and which post meta you pluck out. 

For example, one user commented in a different issue about wanting to pull out custom fields.

**Comment by ChrisRAoW** [comment]
@oguruma1218 Thanks for your question. Rss feeds is a standard format which is used across all kinds of Content Management Systems. This plugin is not Worpdress specific, but should cover a wide range of systems.
