### ISSUE TITLE
Author tag not rendering

### ISSUE THREAD

**Issue by shmaltz** [ChrisRAoW/mautic-rss-to-email-bundle#58]
In my feed I have both the `<dc:creator>` and `<author>` tags filled in and they show up properly in the feed, however when I put `{feeditem:author}` in my template, it doesn't display the author name...
Am I doing something wrong?

I also tried the `{feeditem:categories}` tag, using `<category>Category Name</category>` in my feed, and that didn't work either.

Title, description etc. works properly.

**Comment by ChrisRAoW** [comment]
@shmaltz Can you send the link to your RSS feed? If you don't want to post it here you can also sent it by e-mail chris[at]raow[dot]nl

**Comment by shmaltz** [comment]
Hi! For some reason when I was sending the test mail it wasn't working, however when the campaign actually sent, it worked!
Thanks for this awesome plugin!
