### ISSUE TITLE
Output of feed-items in text-email/text-version

### ISSUE THREAD

**Issue by iparker** [ChrisRAoW/mautic-rss-to-email-bundle#59]
Hello,

should the output of the feeditems also work in the txt-version of the email?

I tried it with the following simple structure and get no feed output in the txt-mail:

{feed url="myurl"}
{feeditems count="5"}
{feeditem:title}

{/feeditems} 
{/feed}

Thanks for some help!

Best regards,

Timo

**Comment by ChrisRAoW** [comment]
@iparker Currently it only works in de HTML version. But great question / suggestion. I will check if I can make ik work in the txt-version as well.

**Comment by ChrisRAoW** [comment]
@iparker This was fixed in the latest 1.6.0 release
