### ISSUE TITLE
Mautic stops loading after composer install

### ISSUE THREAD

**Issue by pradeepm** [ChrisRAoW/mautic-rss-to-email-bundle#6]
Hi, I managed to install this and get it to work fine on a Bitnami Mautic instance on AWS. I've been trying to do the same on an Ubuntu Server instance but every time I install this, Mautic stops loading. I tried installing Mautic first and then this and it didn't work. So I thought I'll install this on the Mautic folder before I install/configure Mautic. Did that and the Mautic installer isn't coming up any more... Any thoughts or guidelines to figure out what's going on? As it's a brand new server with no sensitive data, I'm more than happy to give you the access too. Many thanks in advance.

**Comment by ChrisRAoW** [comment]
@pradeepm I'm happy to help. Did you already checked the log files? 

I could also check directly on your server. Can you send the inlogdetails to chris[at]raow.nl?

**Comment by pradeepm** [comment]
Hello Chris, please check your emails. Thanks.

**Comment by ChrisRAoW** [comment]
Replied your email. 

Mautic was installed from the ZIP downloaded from the Mautic website. This doenst include the composer.json. So when you run the `composer install` all the required libraries from the vendor folder are removed. 

So for others stumbling on the same issue:
- Or install mautic from the Git (https://github.com/mautic/mautic)
- Or download the composer.json from the Mautic GIT and place it in the root of your mautic installation.

**Comment by pradeepm** [comment]
Many thanks Chris! For the help and the explanation. Keep up the good work.
