### ISSUE TITLE
Problem with html-encoding in feed-url

### ISSUE THREAD

**Issue by iparker** [ChrisRAoW/mautic-rss-to-email-bundle#60]
Hello,

we have a problem with out feed-url because they contain multiple get parameter.

The url is something like 
https://www.url.de/api/endpoint.rss?param1=value1&order[random]&itemsPerPage=5&top_offer=1&sponsored=1

But inside the mautic editor happens some kind of html-encoding, so the url is saved as

https://www.url.de/api/endpoint.rss?param1=value1&amp;order[random]&amp;itemsPerPage=5&amp;top_offer=1&amp;sponsored=1

And this makes problems with fetching the items from the feed.

We make a simple solution: just replace &amp; with & in the feed url.

Best regards,

Timo

**Comment by ChrisRAoW** [comment]
@iparker What version of mautic are you using?

**Comment by iparker** [comment]
We are using 4.0.1 or 4.1.1 but with the legacy email editor.

**Comment by ChrisRAoW** [comment]
@iparker Alright...Will try to look into it soon, currently really busy with other projects.

**Comment by ChrisRAoW** [comment]
@iparker This was fixed in the latest 1.6.0 release

**Comment by TornMarketing** [comment]
How are we handling html encoding for the broader piece?

Getting the quotes to be encoded in both html and mjml
Mautic V4.0 - V4.4

```
<mj-raw>
	  {feed url=&quot;https://www.domain.com/feeds/posts/rss/&quot;}
	  {feeditems}
	  <h3>{feeditem:title}
	  </h3>
	  <p>
		<small>{feeditem:date format=&quot;d-m-Y H:i&quot;}</small>
	  </p>
	  <p>{feeditem:description}
	  </p>
	  <p>
		<img src="{feeditem:image}"/>
	  </p>
	  {/feeditems}
	  {/feed}
	</mj-raw>
```

**Comment by ChrisRAoW** [comment]
@TornMarketing Interesting. If you replace the "&quot;" by the correct character manually will be changed back after save?

**Comment by TornMarketing** [comment]
> @TornMarketing Interesting. If you replace the "&quot;" by the correct character manually will be changed back after save?

Yeah cycle's back on save

Mautic implement the encode a while back to clean code (over a yr ago), has effected my style selectors 

Donno how the issue hasn't come up before

**Comment by ChrisRAoW** [comment]
@TornMarketing Haven't experienced it so far either. Not another plugin installed recently that can cause this?

**Comment by TornMarketing** [comment]
> @TornMarketing Haven't experienced it so far either. Not another plugin installed recently that can cause this?

Tried on a few different instances, 
Latest was brand new default config

**Comment by ChrisRAoW** [comment]
@TornMarketing Ah, then it's something I have to check. Can you give me some steps to reproduce the issue?

**Comment by TornMarketing** [comment]
> @TornMarketing Ah, then it's something I have to check. Can you give me some steps to reproduce the issue?

Thinking on this further 
Wondering it's a database thing

My old mautic ticket I neglected to follow up on when I might ate from 3 to 4, effectively the same issue 

https://github.com/mautic/mautic/issues/10508

**Comment by ChrisRAoW** [comment]
I'm quite busy currently, but I will try to find out if this is something I can reproduce too. Can you give me some steps nevertheless?

**Comment by TornMarketing** [comment]
> I'm quite busy currently, but I will try to find out if this is something I can reproduce too. Can you give me some steps nevertheless?

Recreation
Mjml mj-raw
Copy n paste from github, update url, save, test send

Html code
Same as above
