### ISSUE TITLE
Not a valid RSS /ATOM feed. Weird, its WP outputting the xml

### ISSUE THREAD

**Issue by NJseo** [ChrisRAoW/mautic-rss-to-email-bundle#61]
This one has got me for a loop. Invalid rss feed. Its default wordpress. Trying to find a plugin that outputs valid rss.

Error: A feed could not be found at `https://www.multiculturalcaregiving.net/post-sitemap1.xml`. This does not appear to be a valid RSS or Atom feed.

**Comment by ChrisRAoW** [comment]
@NJseo This is not a valid feed:
https://www.multiculturalcaregiving.net/post-sitemap1.xml

You should use this url:
https://www.multiculturalcaregiving.net/feed/

**Comment by NJseo** [comment]
Thank you so much Chris
