### ISSUE TITLE
no images in feed

### ISSUE THREAD

**Issue by lgwapnitsky** [ChrisRAoW/mautic-rss-to-email-bundle#62]
I can see preview images in other readers, but this is not picking up the images properly.  Ideas?

My feed is at https://larry.wapnitsky.com/feed/feed.xml

**Comment by ChrisRAoW** [comment]
@lgwapnitsky The image must be referenced in the `<enclosure>` or the `<media>` tag.

**Comment by ChrisRAoW** [comment]
Since no future reply I assume this fixed the issue. Will close issue
