### ISSUE TITLE
Unknown namespace mautic.org/rss/mautic

### ISSUE THREAD

**Issue by kuzmany** [ChrisRAoW/mautic-rss-to-email-bundle#66]
Because https://www.mautic.org/rss/mautic/ return 404
Can you share original namespaces  definition? We can make it alive.

**Comment by ChrisRAoW** [comment]
@kuzmany What do you mean with namespace definition?

**Comment by kuzmany** [comment]
What content was on the https://www.mautic.org/rss/mautic/ ?
I just follow documentation 

> Add this to the xmlns definitions in your RSS-feed: xmlns:mautic="https://www.mautic.org/rss/mautic/"

And this URL return 404.  I suppose to this address should return something.
Custom tags does not work at the moment.

**Comment by ChrisRAoW** [comment]
@kuzmany The url doenst have to return anything. It not an url but an uri. The uri declares the namespace itself.

**Comment by kuzmany** [comment]
Now I found the issue. It was my mistake

**Comment by ChrisRAoW** [comment]
@kuzmany Good to hear!
