### ISSUE TITLE
Cannot install via Composer in Mautic 4.4.1

### ISSUE THREAD

**Issue by TonyBogdanov** [ChrisRAoW/mautic-rss-to-email-bundle#69]
I am unable to install this plugin with Composer 2 in Mautic 4.4.1.

I'm using `composer require raow/mautic-rss-to-email-bundle:1.7.0`, and the result is:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
  - Root composer.json requires mautic/core-lib ^4.0 -> satisfiable by mautic/core-lib[4.3.x-dev].
  - mautic/core-lib 4.3.x-dev requires friendsofsymfony/oauth-server-bundle dev-master -> found friendsofsymfony/oauth-server-bundle[dev-master, 2.0.x-dev (alias of dev-master)] but the package is fixed to dev-doctrine-fix (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

For your convenience, here's a simple `Dockerfile` to reproduce the issue:

```
FROM alpine:3.13

RUN apk add git curl php php-phar php-json php-curl php-iconv php-openssl
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

RUN git clone --single-branch -b 4.4.1 https://github.com/mautic/mautic.git
WORKDIR mautic

RUN apk add php-dom php-tokenizer php-imap php-fileinfo php-pdo php-xmlwriter php-sockets php-zip php-bcmath php-xml \
    php-simplexml php-gd php-xmlreader
RUN composer install

# All works up until the next line.
RUN composer require raow/mautic-rss-to-email-bundle:1.7.0
```

**Comment by ChrisRAoW** [comment]
@TonyBogdanov currently I don't have the mautic composer plugin inside the composer.json. I'm not sure if that is the reason you are getting this error, but I think it at least the reason you can't install it.

**Comment by TonyBogdanov** [comment]
@ChrisRAoW If you are talking about `mautic/composer-plugin`, I think that one is deprecated. It only supports Composer 1 and Mautic 4 uses Composer 2 now. Honestly I don't really understand what the error means...

**Comment by ChrisRAoW** [comment]
@TonyBogdanov Ah oke, I was not aware.

Do you use this way of installing plugins through composer for other plugins?

**Comment by TonyBogdanov** [comment]
@ChrisRAoW I use it for one more plugin and it has similar issues, so I chose to just install them both by extracting a downloaded ZIP archive. Less headache.

**Comment by ChrisRAoW** [comment]
@TonyBogdanov Can we draw the conclusion that this is not really an issue of this plugin?

**Comment by TonyBogdanov** [comment]
@ChrisRAoW I can't really say where the problem is, the fact of the matter is that Mautic install just fine with Composer 2, but trying to `require` this plugin fails, so something with the plugin is wrong.. exactly what, I don't know yet.

**Comment by ChrisRAoW** [comment]
@TonyBogdanov But you had the same issue with other plugins too right?

**Comment by ChrisRAoW** [comment]
Closed due to inactivity
