### ISSUE TITLE
Fetching only new posts

### ISSUE THREAD

**Issue by pradeepm** [ChrisRAoW/mautic-rss-to-email-bundle#7]
Hello Chris,

This is not quite an 'issue' but is there a way for the plugin to fetch only the 'new' posts? Basically I'm trying to build a weekly newsletter so it fetches the posts published since the last newsletter (similar to what MailChimp does). Further, this is more of a Mautic question, is there a way for us to automate to go out weekly or we just have to create a load of campaigns/emails with published date set to the dates we want those to go out? 

Many thanks in advance.

**Comment by ChrisRAoW** [comment]
Question 1:
Nu it does not at the moment. You could play with the count in the feeditems token: `{feeditems count="3"}`. But i agree i would be a nice feature.

Question 2:
Currently I'm using this plugin for it: https://github.com/thirdset/ThirdSetMauticResetBundle. 
But some good news....the new version of Mautic (2.14) which will be release at the end of this month has recuring campaigns buildin.

**Comment by pradeepm** [comment]
Many thanks again. Hopefully you will find the ideas and time to make this even better in future.
