### ISSUE TITLE
Not compatible with PHP 8

### ISSUE THREAD

**Issue by ttencate** [ChrisRAoW/mautic-rss-to-email-bundle#70]
> [2022-12-20 09:29:41] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "implode(): Argument #2 ($array) must be of type ?array, string given" at /var/www/vhosts/mautic.veganchallenge.nl/httpdocs/plugins/MauticRssToEmailBundle/vendor/simplepie/simplepie/library/SimplePie/Parse/Date.php line 544 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): implode(): Argument #2 ($array) must be of type ?array, string given at /var/www/vhosts/mautic.veganchallenge.nl/httpdocs/plugins/MauticRssToEmailBundle/vendor/simplepie/simplepie/library/SimplePie/Parse/Date.php:544)"}

The reverse order of `implode()` arguments was finally removed in PHP 8. This looks like https://github.com/simplepie/simplepie/issues/718 in SimplePie, which was fixed in 1.5.3, but MauticRssToEmailBundle still has 1.5.2 in its `composer.lock` file.

Updating simplepie should suffice.

**Comment by ChrisRAoW** [comment]
@ttencate Thanks for letting me know. Will check if I can update simplepie to latest version which is 1.7 at the moment.

**Comment by bdacus01** [comment]
version 1.5.7 works fine.

**Comment by ChrisRAoW** [comment]
@bdacus01 I just updated the bundled Simpliepie version to version 1.5.8

**Comment by ChrisRAoW** [comment]
@bdacus01 By default wordpress is not including the images in the rss feed. You need an extra plugin for that that add a media or enclosure tag to the items in the feed.

**Comment by bdacus01** [comment]
Just put this in my functions.php of my child theme.  Works brilliant thanks again...  Hit me up if you need testing help.


`function featuredtoRSS($content) {
global $post;
if ( has_post_thumbnail( $post->ID ) ){
$content = '<div>' . get_the_post_thumbnail( $post->ID, 'medium', array( 'style' => 'margin-bottom: 15px;' ) ) . '</div>' . $content;
}
return $content;
}
 
add_filter('the_excerpt_rss', 'featuredtoRSS');
add_filter('the_content_feed', 'featuredtoRSS');`

**Comment by miamicityman** [comment]
Just upgraded PHP 8.0 from 7.4 and got the same error as originally at line 544. Was **simplepie** ever updated?
