### ISSUE TITLE
Error: URL () empty or not valid

### ISSUE THREAD

**Issue by ivfarias** [ChrisRAoW/mautic-rss-to-email-bundle#73]
Hey, I'm having a bit of a hard time getting the plugin to work.

I tried the following approaches:

1. Used the "Code mode" and added the feed code inside a data-slot

`<div data-slot="2">
<div data-slot-container="2">
{feed url="https://www.kyte.com.br/blog/rss.xml"}
{feeditems}
        <h3>{feeditem:title}</h3>
        <p><small>{feeditem:date format="d-m-Y H:i"}</small></p>
        <p>{feeditem:description}</p>
        <p><img src="{feeditem:image}"></p>
    {/feeditems}
{/feed}
</div>
</div>`

Is this case nothing is returned.

2. Added a 'raw' block to an email template

`	<mj-raw>
	  {feed url="https://www.kyte.com.br/blog/rss.xml"}
	  {feeditems}
	  <h3>{feeditem:title}
	  </h3>
	  <p>
		<small>{feeditem:date format="d-m-Y H:i"}</small>
	  </p>
	  <p>{feeditem:description}
	  </p>
	  <p>
		<img src="{feeditem:image}"/>
	  </p>
	  {/feeditems}
	  {/feed}
	</mj-raw>`

In this case I get Error: URL () empty or not valid (which I believe is because grapejs replaces quotes with &quot;

Any idea on how to fix it?

**Comment by ChrisRAoW** [comment]
WIll dive into it. will let you know.

**Comment by ivfarias** [comment]
I figured it out, @ChrisRAoW. The script won't work unless it is nested inside a `<div data-slot="text"></div>` tag. I'll send a PR adding more installation and use instructions to the readme file.

**Comment by ChrisRAoW** [comment]
Nice! Thanks you!
