### ISSUE TITLE
Is Mautic 5 ready?

### ISSUE THREAD

**Issue by pabloveintimilla** [ChrisRAoW/mautic-rss-to-email-bundle#78]
Hi,
 is compatible with Mautic 5?

I had install in mautic 5 with composer but not appear in the plugin section.

Regards!

**Comment by ChrisRAoW** [comment]
@pabloveintimilla It is. Please remove te contents of your cache folder and try again.

**Comment by pabloveintimilla** [comment]
ok thanks!
