### ISSUE TITLE
{feeditem:link}

### ISSUE THREAD

**Issue by dougysobi** [ChrisRAoW/mautic-rss-to-email-bundle#8]
Hi again and thanks for the last reply. I was wondering if you can point at the code where the {feeditem:link} tag for instance is interpreted? Do you have any doc to help me to figure out how this works?
Thanks in advance!

Ju

**Comment by ChrisRAoW** [comment]
Sorry, I do not understand your question.

Do you mean this file:
https://github.com/ChrisRAoW/mautic-rss-to-email-bundle/blob/master/Parser/ItemTag.php

On line 32?

**Comment by dougysobi** [comment]
yes it wasn't clear... I was just blind and couldn't find the way you parsed the {feed:} but it is actually in parser/parser.php line 15. We try to use your code as a start to make the same for xml and json reports to get them sent by email through mautic that's why I try to figure out litle by litle what you've done so far! thanks anyway!
