### ISSUE TITLE
Transactional settings for Mautic 5

### ISSUE THREAD

**Issue by miamicityman** [ChrisRAoW/mautic-rss-to-email-bundle#81]
Hell Chris,

Finally migrating to Mautic 5. 

Any particular configuration requirements for the RSS plugin? Especially re: the transactional settings?

We do a lot of periodical content mailings. Are they still considered transactional? Or are now marketing? 

How would they unsubscribe if they are labeled "transactional"?

Regards,

**Comment by ChrisRAoW** [comment]
@miamicityman I think all those question are unrelated to this plugin / functionality. This plugin only allows you to use some merge tags which will be replaced by the content of the rss feed. Setting regarding transactional or not are not taken into considering by the plugin.

**Comment by miamicityman** [comment]
Thank you!
