### ISSUE TITLE
Image and Categories tags not picking up value

### ISSUE THREAD

**Issue by pradeepm** [ChrisRAoW/mautic-rss-to-email-bundle#9]
Hello Chris,

I've been trying to build a customised newsletter for a client and tried all available tags to see what do they deliver when it parses my client's WordPress site. Most work well but I noticed that image and category data are not getting displayed correctly. [Here's the link to the sample](https://newsletter.advantagesofage.com/email/preview/8) and [here is the feed I'm using](https://advantagesofage.com/category/exclusives/feed/). Any thoughts? 

Further, if we want to parse additional or custom tags, can we do that by changing php codes directly on the already installed plugin? I know it's not the best way to do it but theoretically would that work? If it would, what are the files we need to specifically look at? 

Many thanks in advance.

**Comment by ChrisRAoW** [comment]
By default Wordpress doesn't include the featured images in the feed. This can be fixed with this plugin: https://wordpress.org/plugins/wp-feed-post-thumbnail/ (there are more). Install it and configure it and it should work right away.

The categories aren't implemented correctly on my end. Will try to fix this today.

If you want to have additional tags we could add them to the plugin. Do you already have some tags in mind?

**Comment by pradeepm** [comment]
We have added featured images through functions.php not through a plugin.
Would that make any difference?

Tags we like to parse are custom tags specific to a project. Like Original
Price, Sale Price, Offer Percentage etc, Not sure if it's fair to expect
them from this. On the other hand such tags would be immensely useful for a
product feed such as a Woocommerce products feed.
--
Most of the important things in the world have been accomplished by people
who have kept on trying when there seemed to be no hope at all - Dale
Carnegie

**Comment by ChrisRAoW** [comment]
That wouldn't make any difference. But the RSS should contain an media or enclosure tag containing the url to the image.

We use the SimplePie library to parse the RSS / XML file. If simplepie has a solution the parse it from the xml we can create a solution map it to the Email. Do you have an xml already containing this information?

I just release an update of the plugin which fixed parsing the categories.

**Comment by pradeepm** [comment]
Here's how images appear with the feed:

<description><![CDATA[<div><img width="770" height="513"
src="https://i1.wp.com/advantagesofage.com/app/uploads/2018/03/senior-cohousing-14-770.jpg?fit=770%2C513&amp;ssl=1"
class="attachment-full size-full wp-post-image" alt=""
style="margin-bottom: 15px;"
srcset="https://i1.wp.com/advantagesofage.com/app/uploads/2018/03/senior-cohousing-14-770.jpg?w=770&amp;ssl=1
770w, https://i1.wp.com/advantagesofage.com/app/uploads/2018/03/senior-cohousing-14-770.jpg?resize=300%2C200&amp;ssl=1
300w, https://i1.wp.com/advantagesofage.com/app/uploads/2018/03/senior-cohousing-14-770.jpg?resize=24%2C16&amp;ssl=1
24w, https://i1.wp.com/advantagesofage.com/app/uploads/2018/03/senior-cohousing-14-770.jpg?resize=36%2C24&amp;ssl=1
36w, https://i1.wp.com/advantagesofage.com/app/uploads/2018/03/senior-cohousing-14-770.jpg?resize=48%2C32&amp;ssl=1
48w" sizes="(max-width: 770px) 100vw, 770px" /></div>Far from a
commune or coop, these planned villages are no less about cooperation
and community. Read the full article here: For Active Seniors,
Cohousing Offers A Cozier Alternative To Downsizing &#124;
KHN]]></description>

It displays the image within description area but not in where we use the
tag to display the image.

I've asked my developer to have a look at the SimplePie library and make
changes to his XML files to comply with SimplePie. I'll get back to you
when I have an update from them.
--
Most of the important things in the world have been accomplished by people
who have kept on trying when there seemed to be no hope at all - Dale
Carnegie

**Comment by ChrisRAoW** [comment]
You include the image now in the description. But it should be in its own media of enclosure tag. The plugin a suggested does just that.

**Comment by pradeepm** [comment]
We tried with this, outside the Description tag but still no luck:

<image><img src="https://www.frugl.com/wp-content/uploads/2018/06/163034925663-small.jpg"/></image>

Any suggestions?
--
Most of the important things in the world have been accomplished by people
who have kept on trying when there seemed to be no hope at all - Dale
Carnegie

**Comment by ChrisRAoW** [comment]
This isn’t going to work. You need the media or enclosure tag.
http://www.rssboard.org/media-rss <http://www.rssboard.org/media-rss>






Chris Schrijver
Eigenaar
Stationsplein 4
3844 KR Harderwijk
	0341 - 75 15 15 <tel:+31341751515>
06 - 13 69 07 78 <tel:+31613690778>
chris@raow.nl <mailto:chris@raow.nl>
www.raow.nl <http://www.raow.nl/>

> Op 25 jun. 2018, om 14:59 heeft pradeepm <notifications@github.com> het volgende geschreven:
> 
> We tried with this, outside the Description tag but still no luck:
> 
> <image><img src="https://www.frugl.com/wp-content/uploads/2018/06/163034925663-small.jpg"/></image>
> 
> Any suggestions?
> --
> Most of the important things in the world have been accomplished by people
> who have kept on trying when there seemed to be no hope at all - Dale
> Carnegie
> 
>

**Comment by pradeepm** [comment]
Oh I'm with you now. Will this format work or does it need more information?

<media:content url="http://xyz.com/example.jpg" medium="image">

--
Most of the important things in the world have been accomplished by people
who have kept on trying when there seemed to be no hope at all - Dale
Carnegie

**Comment by ChrisRAoW** [comment]
This should work. But like I said, the plugin I suggested does already exactly this.

Chris






Chris Schrijver
Eigenaar
Stationsplein 4
3844 KR Harderwijk
	0341 - 75 15 15 <tel:+31341751515>
06 - 13 69 07 78 <tel:+31613690778>
chris@raow.nl <mailto:chris@raow.nl>
www.raow.nl <http://www.raow.nl/>

> Op 25 jun. 2018, om 15:09 heeft pradeepm <notifications@github.com> het volgende geschreven:
> 
> Oh I'm with you now. Will this format work or does it need more information?
> 
> <media:content url="http://xyz.com/example.jpg" medium="image">
> 
> --
> Most of the important things in the world have been accomplished by people
> who have kept on trying when there seemed to be no hope at all - Dale
> Carnegie
> 
>

**Comment by pradeepm** [comment]
Many thanks! I have two projects going on. One is standard WordPress blog
which I can use that plugin. The other is a different site where we have to
manually build the feed.
--
Most of the important things in the world have been accomplished by people
who have kept on trying when there seemed to be no hope at all - Dale
Carnegie
